/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.wxdoctor;

public final class R {
    public static final class anim {
        public static final int push_left_in=0x7f040000;
        public static final int push_left_out=0x7f040001;
        public static final int push_right_in=0x7f040002;
        public static final int push_right_out=0x7f040003;
        public static final int push_top_in=0x7f040004;
        public static final int push_top_out=0x7f040005;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int aichong_bg=0x7f050016;
        public static final int animal_age_text=0x7f050019;
        public static final int bg=0x7f050000;
        public static final int blue=0x7f050006;
        public static final int blue_btn=0x7f050017;
        public static final int check_code_btn=0x7f05001e;
        public static final int check_code_btn_down=0x7f05001d;
        public static final int desc=0x7f050004;
        public static final int find_home_detail_text=0x7f050015;
        public static final int hint=0x7f050005;
        public static final int key_item_bg=0x7f05000a;
        public static final int line=0x7f050008;
        public static final int list_line=0x7f050009;
        public static final int login_btn_down=0x7f050010;
        public static final int login_text_color=0x7f050013;
        public static final int main_bg=0x7f05001a;
        public static final int main_menu_bg=0x7f050001;
        public static final int main_tab_bg=0x7f05001f;
        public static final int menu=0x7f050003;
        public static final int miaodou_bg=0x7f05000b;
        public static final int miaodou_btn_text_bg=0x7f05001c;
        public static final int my_submit_title=0x7f050018;
        public static final int open_door_modify_bg=0x7f05000e;
        public static final int orign=0x7f050014;
        public static final int register_bg=0x7f050012;
        public static final int register_blue=0x7f05000d;
        public static final int register_line=0x7f050007;
        public static final int register_textinfo=0x7f05000c;
        public static final int relative_bg=0x7f05001b;
        public static final int searchview_bg=0x7f050020;
        public static final int submit=0x7f050011;
        public static final int text_grey=0x7f05000f;
        public static final int title=0x7f050002;
    }
    public static final class drawable {
        public static final int back_btn=0x7f020000;
        public static final int ic_launcher=0x7f020001;
        public static final int main_line=0x7f020002;
        public static final int main_list_header=0x7f020003;
        public static final int main_tab_wodexinxi_selected=0x7f020004;
        public static final int main_tab_wodexinxi_unselected=0x7f020005;
        public static final int main_tab_wodezhensuo_selected=0x7f020006;
        public static final int main_tab_wodezhensuo_unselected=0x7f020007;
        public static final int main_tab_zhuanjiazixun_selected=0x7f020008;
        public static final int main_tab_zhuanjiazixun_unselected=0x7f020009;
        public static final int search_icon=0x7f02000a;
    }
    public static final class id {
        public static final int Checkin_search=0x7f080002;
        public static final int actionbar_back=0x7f080000;
        public static final int actionbar_title=0x7f080001;
        public static final int main_activity_myexpert_rb=0x7f080006;
        public static final int main_activity_myinfo_rb=0x7f080007;
        public static final int main_activity_myroom_rb=0x7f080005;
        public static final int main_activity_radiogroup=0x7f080004;
        public static final int main_activity_top=0x7f080003;
        public static final int main_list_item_age_textview=0x7f08000e;
        public static final int main_list_item_babyinfo_textview=0x7f08000d;
        public static final int main_list_item_header_imageview=0x7f08000b;
        public static final int main_list_item_header_textview=0x7f08000c;
        public static final int main_list_listview=0x7f080008;
        public static final int main_list_nodata_textview=0x7f08000a;
        public static final int main_no_list=0x7f080009;
    }
    public static final class layout {
        public static final int action_bar=0x7f030000;
        public static final int actionbar_home=0x7f030001;
        public static final int commp_searchview=0x7f030002;
        public static final int main_activity=0x7f030003;
        public static final int main_list=0x7f030004;
        public static final int main_list_item=0x7f030005;
    }
    public static final class string {
        public static final int app_name=0x7f060000;
        public static final int click_again_to_exit=0x7f060006;
        public static final int main_list_nodata=0x7f060005;
        public static final int main_tab_expert=0x7f060003;
        public static final int main_tab_myinfo=0x7f060004;
        public static final int main_tab_myroom=0x7f060002;
        public static final int search=0x7f060001;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f070000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f070001;
    }
}
